<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SocketChat.Application\SocketChat.Application.csproj" />
    <ProjectReference Include="..\SocketChat.Domain\SocketChat.Domain.csproj" />
  </ItemGroup>

</Project>
